    name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend smoke
        run: |
          cd backend
          python -c "from quantum_ai_optimizer.app import app; print('app imported')"
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
